name: Bug
description: Template para registrar bugs no projeto
title: "`[BUG]` - Título"
labels:
  - "bug"
# Validações do tipo 'required' apenas funcionam em repositórios públicos, talvez venham a funcionar futuramente em repositórios privados.

body:
  - type: textarea
    id: showcase
    attributes:
      label: Informações
    validations:
      required: true

  - type: textarea
    id: print
    attributes:
      label: Prints
    validations:
      required: true
  